server:
  port: 9292

spring:
  datasource:
    username: root
    password: Msq++hsk%1955
    url: jdbc:mysql://localhost:3306/java_react
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    open-in-view: true

    hibernate:
      ddl-auto: create
      format_sql: true
